# Generated by Django 4.1.6 on 2023-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
