# Generated by Django 4.1.6 on 2023-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancysettings',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
