# Generated by Django 4.1.6 on 2023-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_rename_data_vacancysettings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancysettings',
            name='date',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
