# Generated by Django 4.1.6 on 2023-02-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_vacancysettings_date_vacancy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
